# DMA Test Application Configuration

CONFIG_DMA=y
CONFIG_LOG=y
CONFIG_DMA_LOG_LEVEL_DBG=y
CONFIG_PRINTK=y

# Enable GPIO for LED status indicator
CONFIG_GPIO=y

# Immediate logging to see crash dumps
CONFIG_LOG_MODE_IMMEDIATE=y

# Late Console Init to override UART hook with SDI
CONFIG_CONSOLE_INIT_PRIORITY=40

CONFIG_SDI_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_LOG_PRINTK=y

