CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_SDI_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_PM_WCH=y
CONFIG_PM_DRIVERS=y
CONFIG_RTC=y
CONFIG_RTC_ALARM=n

# Use SysTick for system timer
CONFIG_WCH_LPTIM_TIMER=n
CONFIG_CORTEX_M_SYSTICK=n
CONFIG_CH32V00X_SYSTICK=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# Enable debugging information for RTC and PM
CONFIG_RTC_LOG_LEVEL_DBG=y
# CONFIG_PM_LOG_LEVEL_DBG=y
